---
version: "3.7"

services:
  postgres:
    image: postgres:11.2
    environment:
      - PGDATA: /data
    volumes:
      - postgres-data:/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  default:
    driver: bridge
