---
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    default: true
    url: http://prometheus:9090
    access: proxy
  - name: Jaeger
    type: jaeger
    url: http://jaeger:16686
    access: proxy
