---
global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: pg2pubsub
    static_configs:
      - targets: ["host.docker.internal:9525"]
    relabel_configs: &relabel
      - source_labels: [__address__]
        regex: .+:(\d+)
        target_label: port
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.+):\d+
        target_label: instance
        replacement: ${1}
